### ISSUE TITLE
practica 9

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-maetzy-quetzaly-angel-jesus#1]
[induccion matematica.pdf](https://github.com/user-attachments/files/17535695/induccion.matematica.pdf)

**Comment by AlynGomez12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:23/25
Total:98/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
